version: '3'

services:   

    app:
        build: 
            context: ./
            dockerfile: Dockerfile.node
        container_name: app        
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s
        volumes:             
            - ./node:/usr/src/app 
            - /usr/src/app/node_modules            
        networks: 
            - node-network     
        ports: 
            - 3000:3000           
        depends_on: 
            - db          
        tty: true  
        restart: always
        command: node index.js    

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db_mysql
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root            
        networks: 
            - node-network
        ports: 
            - 3306:3306
        restart: always
        tty: true

    nginx:
        build: 
            context: ./
            dockerfile: Dockerfile.nginx
        container_name: srv-nginx          
        ports: 
            - 8080:80
        networks: 
            - node-network       
        tty: true
        restart: always
        depends_on: 
            - app

networks:
    node-network:
        driver: bridge