version: '3'

services:   

    app:
        image: htaf83/srv-node
        container_name: app        
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
        volumes: 
            - ./node:/usr/src/app         
        networks: 
            - node-network     
        ports: 
            - 3000:3000           
        depends_on: 
            - db
        tty: true      

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db_mysql
        restart: always
        tty: true
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root            
        networks: 
            - node-network
        ports: 
            - 3306:3306

    nginx:
        image: htaf83/srv-nginx-node
        container_name: srv-nginx        
        ports: 
            - 8080:80
        networks: 
            - node-network       
        tty: true
        depends_on: 
            - app

networks:
    node-network:
        driver: bridge